name: 'AWS deploy with Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Initialize Terraform
      run: terraform init
      working-directory: iac/environments/prod
      
    - name: Validate Terraform
      run: terraform validate
      working-directory: iac/environments/prod

    - name: Terraform Plan
      run: terraform plan
      working-directory: iac/environments/prod

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: iac/environments/prod
