name: "AWS deploy with Terraform"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular_build_artifact
          path: dist/angular-terraform/browser
          retention-days: 1

  deploy-job:
    name: "AWS deploy with Terraform"
    needs: build-job
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download angular build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular_build_artifact
          path: dist

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: iac/environments/prod

      - name: Validate Terraform
        run: terraform validate
        working-directory: iac/environments/prod

      - name: Terraform Plan
        run: terraform plan -var "angular_build_folder_path=../../../dist"
        working-directory: iac/environments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "angular_build_folder_path=../../../dist"
        working-directory: iac/environments/prod
